### ISSUE TITLE
报错缺少属性

### ISSUE THREAD

**Issue by Dengqlbq** [Unispac/Fight-Poison-With-Poison#1]
1. python visualize.py -method=tsne -dataset=cifar10 -poison_type=adaptive_blend -poison_rate=0.005 -cover_rate=0.005
AttributeError: module 'config' has no attribute 'parser_default'. Did you mean: 'trigger_default'?

2. python poison_cleanser_iter.py -dataset=cifar10 -poison_type=adaptive_blend -poison_rate=0.005 -cover_rate=0.005
AttributeError: module 'confusion_training' has no attribute 'iterative_poison_distillation'

**Comment by Unispac** [comment]
Hi, we are constantly updating our repository recently. 
For now, to launch the cleanser, please run:
python ct_cleanser.py -dataset=cifar10 -poison_type=adaptive_blend -poison_rate=0.005 -cover_rate=0.005
--------------
Note that, current version might not be optimal yet, since we are still updating our implementation.
Thanks!
